# Generated by Django 3.2.5 on 2022-01-08 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('contacto', models.CharField(max_length=250)),
                ('dni', models.CharField(max_length=8)),
                ('observacion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Egresos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=250)),
                ('costos', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=250)),
                ('ruc', models.CharField(max_length=250)),
                ('nombre', models.CharField(max_length=250)),
                ('contacto', models.CharField(max_length=250)),
                ('observaciones', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=250)),
                ('estado', models.CharField(max_length=250)),
                ('encargado', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Vale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=250)),
                ('dni_cliente', models.CharField(max_length=250)),
                ('observaciones', models.CharField(max_length=250)),
                ('marca', models.CharField(max_length=250)),
                ('encargado', models.CharField(max_length=250)),
            ],
        ),
    ]
