# Generated by Django 4.0.1 on 2022-01-10 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cliente_egresos_proveedor_stock_vale_venta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestAdmin',
        ),
    ]
